-- Import data resmi Bantuan Alsintan Kabupaten Way Kanan TA 2025
-- (sumber: Data_Bantuan_Alsintan_Way_Kanan_TA_2025.xlsx, sheet "Rekap" & "Data
-- Alsintan 2025" -- 270 unit, 6 jenis, tersebar di 16 nilai kecamatan).
--
-- Data test/dummy lama di tabel alsintan dihapus total (sudah dikonfirmasi
-- user bukan data produksi asli), diganti data resmi ini.
--
-- Catatan kualitas data sumber (tidak diubah, sesuai apa adanya di Excel):
--  - 1 unit Traktor Roda 2 (WK25-TR2-018, penerima "Kodim Way Kanan 0427")
--    tercatat kecamatan "Way Kanan" -- bukan salah satu dari 15 kecamatan
--    resmi di master_kecamatan. Unit ini akan tetap muncul di total & filter
--    per-jenis, tapi TIDAK akan match di choropleth per-kecamatan (peta)
--    karena nama kecamatannya tidak ada di GeoJSON batas wilayah.

delete from alsintan;

-- Perbaiki penamaan jenis lama ("Traktor Crawler", dari migration 0012) agar
-- konsisten dengan penamaan resmi dokumen TA 2025 ("Traktor Roda Crawler").
update master_jenis_alsintan set nama_jenis = 'Traktor Roda Crawler' where nama_jenis = 'Traktor Crawler';

-- Jaga-jaga bila salah satu dari 6 jenis berikut belum ada di DB.
insert into master_jenis_alsintan (nama_jenis, kategori)
select v.nama_jenis, v.kategori::kategori_alsintan
from (values
  ('Traktor Roda 4', 'pra_panen'),
  ('Traktor Roda Crawler', 'pra_panen'),
  ('Traktor Roda 2', 'pra_panen'),
  ('Pompa Air', 'pra_panen'),
  ('Hand Sprayer', 'pra_panen'),
  ('Rice Transplanter', 'pra_panen')
) as v(nama_jenis, kategori)
where not exists (select 1 from master_jenis_alsintan m where m.nama_jenis = v.nama_jenis);

insert into alsintan (id_unit, id_jenis, tahun_pengadaan, kondisi, penerima, desa, kecamatan) values
  ('WK25-TR4-001', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Rukun Abadi', 'Suka Agung', 'Buay Bahuga'),
  ('WK25-TR4-002', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Harapan Jaya', 'Bumi Agung Wates', 'Bahuga'),
  ('WK25-TR4-003', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Gedung Tani', 'Gedung Pakuon', 'Baradatu'),
  ('WK25-TR4-004', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Karya Tani IV', 'Mulya Sari', 'Negeri Agung'),
  ('WK25-TR4-005', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Purwa Setya Mulya', 'Purwa Agung', 'Negara Batin'),
  ('WK25-TR4-006', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Tohpati Tani', 'Negara Harja', 'Pakuan Ratu'),
  ('WK25-TR4-007', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Tanjung Jaya', 'Pisang Baru', 'Bumi Agung'),
  ('WK25-TR4-008', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Neba Madani', 'Gisting Jaya', 'Negara Batin'),
  ('WK25-TR4-009', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Sido Abadi', 'Suka Agung', 'Buay Bahuga'),
  ('WK25-TR4-010', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Maju Bersama', 'Sri Tunggal', 'Buay Bahuga'),
  ('WK25-TR4-011', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Mitra Tani', 'Bumi Harjo', 'Buay Bahuga'),
  ('WK25-TR4-012', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Jaya Makmur', 'Bima Sakti', 'Negeri Besar'),
  ('WK25-TR4-013', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Prima Jaya Tani', 'Kota Bumi Way Kanan', 'Negeri Agung'),
  ('WK25-TR4-014', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Karya Dadi', 'Tanjung Dalam', 'Bumi Agung'),
  ('WK25-TR4-015', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Bina Usaha', 'Suka Bumi', 'Buay Bahuga'),
  ('WK25-TR4-016', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Karya Tani', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-TR4-017', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Sari Wija', 'Bumi Agung Wates', 'Bahuga'),
  ('WK25-TR4-018', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Lingga Jaya', 'Tegal Mukti', 'Negeri Besar'),
  ('WK25-TR4-019', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Citra Usaha', 'Karangan', 'Bumi Agung'),
  ('WK25-TR4-020', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Tani Jaya Makmur', 'Bumi Agung', 'Bumi Agung'),
  ('WK25-TR4-021', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Bina Tani', 'Bumi Agung Wates', 'Bahuga'),
  ('WK25-TR4-022', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Sepakat', 'Bumi Harjo', 'Buay Bahuga'),
  ('WK25-TR4-023', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Menanti Kertanegara', 'Negara Batin', 'Negara Batin'),
  ('WK25-TR4-024', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Makmur Jaya', 'Kota Dewa', 'Bahuga'),
  ('WK25-TR4-025', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Mulya Jaya', 'Sri Tunggal', 'Buay Bahuga'),
  ('WK25-TR4-026', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Karya Tani', 'Gunung Waras', 'Pakuan Ratu'),
  ('WK25-TR4-027', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Waras Jaya', 'Gunung Waras', 'Pakuan Ratu'),
  ('WK25-TR4-028', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Tani Maju', 'Sriwijaya', 'Umpu Semenguk'),
  ('WK25-TR4-029', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Makmur Sentosa', 'Suka Negeri', 'Gunung Labuhan'),
  ('WK25-TR4-030', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Bina Usaha', 'Serdang Kuring', 'Bahuga'),
  ('WK25-TR4-031', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Budi Rahayu 1', 'Bumi Agung Wates', 'Bahuga'),
  ('WK25-TR4-032', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gabus Jaya', 'Pisang Baru', 'Bumi Agung'),
  ('WK25-TR4-033', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Maju Bersama', 'Way Tuba Asri', 'Way Tuba'),
  ('WK25-TR4-034', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Muji Rahayu', 'Gedung Jaya', 'Negara Batin'),
  ('WK25-TR4-035', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'UPJA Harapan Maju', 'Pisang Indah', 'Bumi Agung'),
  ('WK25-TR4-036', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Sido Makmur', 'Suka Dana', 'Buay Bahuga'),
  ('WK25-TR4-037', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Sari Makmur', 'Sari Jaya', 'Negara Batin'),
  ('WK25-TR4-038', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 4'), 2025, 'baik', 'Gapoktan Bumi Sejahtera', 'Bumi Agung', 'Bumi Agung'),
  ('WK25-TRC-001', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda Crawler'), 2025, 'baik', 'UPJA Bina Usaha', 'Suka Bumi', 'Buay Bahuga'),
  ('WK25-TRC-002', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda Crawler'), 2025, 'baik', 'UPJA Rukun Abadi', 'Suka Agung', 'Buay Bahuga'),
  ('WK25-TRC-003', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda Crawler'), 2025, 'baik', 'UPJA Sari Wija', 'Bumi Agung Wates', 'Bahuga'),
  ('WK25-TRC-004', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda Crawler'), 2025, 'baik', 'Gapoktan Mulya Jaya', 'Sri Tunggal', 'Buay Bahuga'),
  ('WK25-TRC-005', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda Crawler'), 2025, 'baik', 'Gapoktan Bina Tani', 'Bumi Agung Wates', 'Bahuga'),
  ('WK25-TR2-001', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Mekar Jaya', 'Sriwijaya', 'Umpu Semenguk'),
  ('WK25-TR2-002', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Bumi Harapan', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-TR2-003', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Karya Usaha', 'Giri Harjo', 'Bahuga'),
  ('WK25-TR2-004', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Budi Karya 1', 'Bumi Agung Wates', 'Bahuga'),
  ('WK25-TR2-005', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Satria Wirang', 'Pisang Indah', 'Bumi Agung'),
  ('WK25-TR2-006', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Merta Wija', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-TR2-007', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Karya Jaya', 'Serupa Indah', 'Pakuan Ratu'),
  ('WK25-TR2-008', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Bakti Makmur', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-TR2-009', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Maju Lancar', 'Bengkulu Rejo', 'Gunung Labuhan'),
  ('WK25-TR2-010', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Maju Bersama', 'Gunung Sangkaran', 'Blambangan Umpu'),
  ('WK25-TR2-011', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Sido Muncul II', 'Jaya Tinggi', 'Kasui'),
  ('WK25-TR2-012', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Karya Sepakat', 'Banjar Mulya', 'Baradatu'),
  ('WK25-TR2-013', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Mekar Jaya', 'Rantau Temiang', 'Banjit'),
  ('WK25-TR2-014', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Tunas Harapan I', 'Pisang Baru', 'Bumi Agung'),
  ('WK25-TR2-015', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Karya Jaya', 'Gelombang Panjang', 'Kasui'),
  ('WK25-TR2-016', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Puji Rahayu', 'Suma Mukti', 'Way Tuba'),
  ('WK25-TR2-017', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Tunas Karya', 'Argomulyo', 'Banjit'),
  ('WK25-TR2-018', (select id from master_jenis_alsintan where nama_jenis = 'Traktor Roda 2'), 2025, 'baik', 'Kodim Way Kanan 0427', 'Way Kanan', 'Way Kanan'),
  ('WK25-POM-001', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Harapan Maju', 'Tanjung Rejo', 'Negeri Agung'),
  ('WK25-POM-002', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Rukun Makmur', 'Tanjung Rejo', 'Negeri Agung'),
  ('WK25-POM-003', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Karya Barokah 2', 'Tanjung Rejo', 'Negeri Agung'),
  ('WK25-POM-004', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sari Bumi 1', 'Tanjung Rejo', 'Negeri Agung'),
  ('WK25-POM-005', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Indah Makmur', 'Tanjung Rejo', 'Negeri Agung'),
  ('WK25-POM-006', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sido Rukun 1', 'Air Ringkih', 'Rebang Tangkas'),
  ('WK25-POM-007', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Melunus', 'Negara Ratu', 'Pakuan Ratu'),
  ('WK25-POM-008', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sido Makmur', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-POM-009', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Baru Dadi', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-POM-010', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sari Bumi', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-POM-011', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Karya Setia', 'Mulyasari', 'Negeri Agung'),
  ('WK25-POM-012', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Karya Mandiri 2', 'Mulyasari', 'Negeri Agung'),
  ('WK25-POM-013', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sari Nadi', 'Tanjung Serupa', 'Pakuan Ratu'),
  ('WK25-POM-014', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Merta Sari', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-POM-015', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Jaya Makmur', 'Way Agung', 'Buay Bahuga'),
  ('WK25-POM-016', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Harapan Maju I', 'Tanjung Harapan', 'Kasui'),
  ('WK25-POM-017', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Karya Mandiri', 'Kasui Lama', 'Kasui'),
  ('WK25-POM-018', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Swasembada', 'Kasui Lama', 'Kasui'),
  ('WK25-POM-019', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Swakarya', 'Kasui Lama', 'Kasui'),
  ('WK25-POM-020', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Hartomoro', 'Kasui Lama', 'Kasui'),
  ('WK25-POM-021', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Lebuay Jaya', 'Kasui Lama', 'Kasui'),
  ('WK25-POM-022', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Garden Family', 'Jaya Tinggi', 'Kasui'),
  ('WK25-POM-023', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Mekar Sari', 'Gelombang Panjang', 'Kasui'),
  ('WK25-POM-024', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Makmur', 'Kedaton', 'Kasui'),
  ('WK25-POM-025', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Bengkulu Maju', 'Bengkulu', 'Gunung Labuhan'),
  ('WK25-POM-026', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Tunas Baru', 'Karangan', 'Bumi Agung'),
  ('WK25-POM-027', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Bumi Mandiri', 'Tanjung Dalam', 'Bumi Agung'),
  ('WK25-POM-028', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Abadi I', 'Suka Agung', 'Buay Bahuga'),
  ('WK25-POM-029', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Cahya Tani', 'Suka Agung', 'Buay Bahuga'),
  ('WK25-POM-030', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sri Rejeki', 'Kota Baru', 'Negeri Agung'),
  ('WK25-POM-031', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Karya Jaya 1', 'Karya Agung', 'Negeri Agung'),
  ('WK25-POM-032', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Bina Karya 1', 'Bengkulu', 'Gunung Labuhan'),
  ('WK25-POM-033', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Macung Jaya', 'Mesir Ilir', 'Bahuga'),
  ('WK25-POM-034', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Suka Karya 1', 'Bumi Agung Wates', 'Bahuga'),
  ('WK25-POM-035', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Gapoktan Margo Makmur', 'Argo Mulyo', 'Banjit'),
  ('WK25-POM-036', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sumber Agung', 'Gedung Rejo', 'Baradatu'),
  ('WK25-POM-037', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Rukun Santoso', 'Tanjung Agung', 'Pakuan Ratu'),
  ('WK25-POM-038', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'UPJA Neba Madani', 'Gisting Jaya', 'Negara Batin'),
  ('WK25-POM-039', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'UPJA Neba Madani', 'Gisting Jaya', 'Negara Batin'),
  ('WK25-POM-040', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Lestari I', 'Suka Bumi', 'Buay Bahuga'),
  ('WK25-POM-041', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sido Dadi', 'Suka Agung', 'Buay Bahuga'),
  ('WK25-POM-042', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Harapan Jaya', 'Suka Bumi', 'Buay Bahuga'),
  ('WK25-POM-043', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sido Mulyo', 'Suka Agung', 'Buay Bahuga'),
  ('WK25-POM-044', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sido Mulyo I', 'Suka Agung', 'Buay Bahuga'),
  ('WK25-POM-045', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Perintis Tani Makmur', 'Suka Bumi', 'Buay Bahuga'),
  ('WK25-POM-046', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'UPJA Maju Bersama', 'Sri Tunggal', 'Buay Bahuga'),
  ('WK25-POM-047', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'UPJA Maju Bersama', 'Sri Tunggal', 'Buay Bahuga'),
  ('WK25-POM-048', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Suka Tani', 'Bengkulu', 'Gunung Labuhan'),
  ('WK25-POM-049', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Banten', 'Bengkulu Jaya', 'Gunung Labuhan'),
  ('WK25-POM-050', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Konco Tani', 'Pisang Baru', 'Bumi Agung'),
  ('WK25-POM-051', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Gapoktan Restu Harapan Jaya', 'Pisang Baru', 'Bumi Agung'),
  ('WK25-POM-052', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Makmur', 'Bumi Agung Wates', 'Bahuga'),
  ('WK25-POM-053', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Usaha Jaya', 'Dewa Agung', 'Bahuga'),
  ('WK25-POM-054', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sido Maju', 'Bumi Agung', 'Bumi Agung'),
  ('WK25-POM-055', (select id from master_jenis_alsintan where nama_jenis = 'Pompa Air'), 2025, 'baik', 'Sido Makmur', 'Negara Harja', 'Pakuan Ratu'),
  ('WK25-HSP-001', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tunas Baru 1', 'Bumi Harjo', 'Buay Bahuga'),
  ('WK25-HSP-002', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tunas Baru 1', 'Bumi Harjo', 'Buay Bahuga'),
  ('WK25-HSP-003', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tunas Baru 1', 'Bumi Harjo', 'Buay Bahuga'),
  ('WK25-HSP-004', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tunas Baru 1', 'Bumi Harjo', 'Buay Bahuga'),
  ('WK25-HSP-005', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mekar Jaya II', 'Pisang Baru', 'Bumi Agung'),
  ('WK25-HSP-006', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mekar Jaya II', 'Pisang Baru', 'Bumi Agung'),
  ('WK25-HSP-007', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mekar Jaya II', 'Pisang Baru', 'Bumi Agung'),
  ('WK25-HSP-008', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mekar Jaya II', 'Pisang Baru', 'Bumi Agung'),
  ('WK25-HSP-009', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Lohjinawi I', 'Simpang Asam', 'Banjit'),
  ('WK25-HSP-010', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Lohjinawi I', 'Simpang Asam', 'Banjit'),
  ('WK25-HSP-011', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Lohjinawi I', 'Simpang Asam', 'Banjit'),
  ('WK25-HSP-012', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Lohjinawi I', 'Simpang Asam', 'Banjit'),
  ('WK25-HSP-013', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tunas Tani Jaya', 'Tanjung Serupa', 'Pakuan Ratu'),
  ('WK25-HSP-014', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tunas Tani Jaya', 'Tanjung Serupa', 'Pakuan Ratu'),
  ('WK25-HSP-015', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tunas Tani Jaya', 'Tanjung Serupa', 'Pakuan Ratu'),
  ('WK25-HSP-016', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tunas Tani Jaya', 'Tanjung Serupa', 'Pakuan Ratu'),
  ('WK25-HSP-017', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Neki Makmur', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-018', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Neki Makmur', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-019', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Neki Makmur', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-020', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Neki Makmur', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-021', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Wisnu Kerta II', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-022', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Wisnu Kerta II', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-023', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Wisnu Kerta II', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-024', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Wisnu Kerta II', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-025', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Wana Sari', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-026', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Wana Sari', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-027', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Wana Sari', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-028', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Wana Sari', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-029', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Kahuripan', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-030', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Kahuripan', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-031', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Kahuripan', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-032', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Kahuripan', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-033', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Amerta Buana Tani', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-034', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Amerta Buana Tani', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-035', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Amerta Buana Tani', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-036', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Amerta Buana Tani', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-037', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Budi Luhur', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-038', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Budi Luhur', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-039', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Budi Luhur', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-040', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Budi Luhur', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-041', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Amerta Tani', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-042', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Amerta Tani', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-043', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Amerta Tani', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-044', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Amerta Tani', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-045', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Wisnu Asri', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-046', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Wisnu Asri', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-047', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Wisnu Asri', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-048', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Wisnu Asri', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-049', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Jaya', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-050', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Jaya', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-051', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Jaya', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-052', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Jaya', 'Bali Sadhar Utara', 'Banjit'),
  ('WK25-HSP-053', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Tani Maju', 'Bumi Agung', 'Bumi Agung'),
  ('WK25-HSP-054', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Tani Maju', 'Bumi Agung', 'Bumi Agung'),
  ('WK25-HSP-055', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Tani Maju', 'Bumi Agung', 'Bumi Agung'),
  ('WK25-HSP-056', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Tani Maju', 'Bumi Agung', 'Bumi Agung'),
  ('WK25-HSP-057', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tirta Sari 1', 'Bali Sadhar Tengah', 'Banjit'),
  ('WK25-HSP-058', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tirta Sari 1', 'Bali Sadhar Tengah', 'Banjit'),
  ('WK25-HSP-059', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tirta Sari 1', 'Bali Sadhar Tengah', 'Banjit'),
  ('WK25-HSP-060', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tirta Sari 1', 'Bali Sadhar Tengah', 'Banjit'),
  ('WK25-HSP-061', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Guyub Rukun', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-062', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Guyub Rukun', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-063', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Guyub Rukun', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-064', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Guyub Rukun', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-065', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Guyub Rukun', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-066', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Jaya', 'Serupa Indah', 'Pakuan Ratu'),
  ('WK25-HSP-067', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Jaya', 'Serupa Indah', 'Pakuan Ratu'),
  ('WK25-HSP-068', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Jaya', 'Serupa Indah', 'Pakuan Ratu'),
  ('WK25-HSP-069', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Jaya', 'Serupa Indah', 'Pakuan Ratu'),
  ('WK25-HSP-070', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Jaya', 'Serupa Indah', 'Pakuan Ratu'),
  ('WK25-HSP-071', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Sentosa', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-072', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Sentosa', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-073', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Sentosa', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-074', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Sentosa', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-075', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Sentosa', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-076', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Maju Lancar', 'Bengkulu Rejo', 'Gunung Labuhan'),
  ('WK25-HSP-077', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Maju Lancar', 'Bengkulu Rejo', 'Gunung Labuhan'),
  ('WK25-HSP-078', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Maju Lancar', 'Bengkulu Rejo', 'Gunung Labuhan'),
  ('WK25-HSP-079', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Maju Lancar', 'Bengkulu Rejo', 'Gunung Labuhan'),
  ('WK25-HSP-080', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Maju Lancar', 'Bengkulu Rejo', 'Gunung Labuhan'),
  ('WK25-HSP-081', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bakti Makmur', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-082', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bakti Makmur', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-083', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bakti Makmur', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-084', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bakti Makmur', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-085', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bakti Makmur', 'Karang Agung', 'Pakuan Ratu'),
  ('WK25-HSP-086', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Harapan Maju', 'Banjar Ratu', 'Gunung Labuhan'),
  ('WK25-HSP-087', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Harapan Maju', 'Banjar Ratu', 'Gunung Labuhan'),
  ('WK25-HSP-088', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Harapan Maju', 'Banjar Ratu', 'Gunung Labuhan'),
  ('WK25-HSP-089', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Harapan Maju', 'Banjar Ratu', 'Gunung Labuhan'),
  ('WK25-HSP-090', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Harapan Maju', 'Banjar Ratu', 'Gunung Labuhan'),
  ('WK25-HSP-091', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Gapoktan Mandiri', 'Gunung Sari', 'Gunung Labuhan'),
  ('WK25-HSP-092', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Gapoktan Mandiri', 'Gunung Sari', 'Gunung Labuhan'),
  ('WK25-HSP-093', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Gapoktan Mandiri', 'Gunung Sari', 'Gunung Labuhan'),
  ('WK25-HSP-094', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Gapoktan Mandiri', 'Gunung Sari', 'Gunung Labuhan'),
  ('WK25-HSP-095', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Gapoktan Mandiri', 'Gunung Sari', 'Gunung Labuhan'),
  ('WK25-HSP-096', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Sukses', 'Way Tuba', 'Gunung Labuhan'),
  ('WK25-HSP-097', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Sukses', 'Way Tuba', 'Gunung Labuhan'),
  ('WK25-HSP-098', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Sukses', 'Way Tuba', 'Gunung Labuhan'),
  ('WK25-HSP-099', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Sukses', 'Way Tuba', 'Gunung Labuhan'),
  ('WK25-HSP-100', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Tani Sukses', 'Way Tuba', 'Gunung Labuhan'),
  ('WK25-HSP-101', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mekar Jaya', 'Sriwijaya', 'Umpu Semenguk'),
  ('WK25-HSP-102', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mekar Jaya', 'Sriwijaya', 'Umpu Semenguk'),
  ('WK25-HSP-103', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mekar Jaya', 'Sriwijaya', 'Umpu Semenguk'),
  ('WK25-HSP-104', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mekar Jaya', 'Sriwijaya', 'Umpu Semenguk'),
  ('WK25-HSP-105', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mekar Jaya', 'Sriwijaya', 'Umpu Semenguk'),
  ('WK25-HSP-106', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bumi Harapan', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-107', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bumi Harapan', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-108', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bumi Harapan', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-109', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bumi Harapan', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-110', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bumi Harapan', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-111', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Selalu Jaya', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-112', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Selalu Jaya', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-113', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Selalu Jaya', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-114', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Selalu Jaya', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-115', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Selalu Jaya', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-116', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bumi Ramik Ragom', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-117', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bumi Ramik Ragom', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-118', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bumi Ramik Ragom', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-119', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bumi Ramik Ragom', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-120', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Bumi Ramik Ragom', 'Bumi Ratu', 'Umpu Semenguk'),
  ('WK25-HSP-121', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Rukun Santoso', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-122', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Rukun Santoso', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-123', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Rukun Santoso', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-124', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Rukun Santoso', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-125', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Rukun Santoso', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-126', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Rukun Abadi', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-127', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Rukun Abadi', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-128', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Rukun Abadi', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-129', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Rukun Abadi', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-130', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Rukun Abadi', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-131', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Fuji Lestari', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-132', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Fuji Lestari', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-133', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Fuji Lestari', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-134', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Fuji Lestari', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-135', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Fuji Lestari', 'Tanjung Harapan', 'Kasui'),
  ('WK25-HSP-136', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mandiri', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-137', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mandiri', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-138', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mandiri', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-139', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mandiri', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-140', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Mandiri', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-141', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Artomoro', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-142', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Artomoro', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-143', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Artomoro', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-144', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Artomoro', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-145', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Artomoro', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-146', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Maju', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-147', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Maju', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-148', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Maju', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-149', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Maju', 'Kasui Lama', 'Kasui'),
  ('WK25-HSP-150', (select id from master_jenis_alsintan where nama_jenis = 'Hand Sprayer'), 2025, 'baik', 'Karya Maju', 'Kasui Lama', 'Kasui'),
  ('WK25-RTP-001', (select id from master_jenis_alsintan where nama_jenis = 'Rice Transplanter'), 2025, 'baik', 'Tirta Sari 1', 'Bali Sadhar Tengah', 'Banjit'),
  ('WK25-RTP-002', (select id from master_jenis_alsintan where nama_jenis = 'Rice Transplanter'), 2025, 'baik', 'Harapan Maju', 'Banjar Ratu', 'Gunung Labuhan'),
  ('WK25-RTP-003', (select id from master_jenis_alsintan where nama_jenis = 'Rice Transplanter'), 2025, 'baik', 'Saraswati', 'Pisang Indah', 'Bumi Agung'),
  ('WK25-RTP-004', (select id from master_jenis_alsintan where nama_jenis = 'Rice Transplanter'), 2025, 'baik', 'Sido Makmur', 'Pakuan Baru', 'Pakuan Ratu');